### ISSUE TITLE
Windows10更新后无法打开软件

### ISSUE THREAD

**Issue by sindney** [NaoTu/DesktopNaotu#111]
您好，我有一台笔记本
windows10家庭版，版本号1909
被强制升级为
操作系统版本：18363.720
版本后，程序无法打开，进程可以在任务管理器中看到
但无窗口弹出
我其他的设备没有问题
是否有朋友有相同的遭遇，是否是系统补丁的问题？

**Comment by topcss** [comment]
没遇到过这个问题，估计是补丁的问题。

**Comment by sindney** [comment]
嗯嗯 估計是補丁，先close了吧
