### ISSUE TITLE
建议下载地址中的 百度网盘 改为 蓝奏云网盘！

### ISSUE THREAD

**Issue by XIU2** [NaoTu/DesktopNaotu#119]
我看压缩包单个文件不足 100MB，建议将下载地址中的 百度网盘 改为 蓝奏云网盘，毕竟百度网盘不开超级会员的话，速度可能还不如 Releases 呢。。。而蓝奏云则可以满速下载！

**Comment by jiahe007** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
