### ISSUE TITLE
没有看到mac版本的1.6版本

### ISSUE THREAD

**Issue by h-jia** [NaoTu/DesktopNaotu#14]
rt

**Comment by topcss** [comment]
很抱歉，一直太忙没时间更新mac的这个版本，尽快会更新的。

**Comment by h-jia** [comment]
@topcss 感谢提供资源，辛苦。现在Mac版的.km不能直接双击打开（打开后脑图页面为新建状态），希望能顺便修复。赞一下这个版本，是mac上用过的最好的mindmap，没有之一。

**Comment by h-jia** [comment]
@topcss 还有现在不能选择默认的外观（布局和颜色），每次新建需要自己手动调整。

**Comment by topcss** [comment]
有空再加，最近实在太忙了。

**Comment by h-jia** [comment]
看到更新了，赞～辛苦啦～
