### ISSUE TITLE
备注中的GFW语法不支持换行

### ISSUE THREAD

**Issue by Zhang21** [NaoTu/DesktopNaotu#20]
环境：

- Win10.x86_64
- v0.1.7

<br>

---

<br>

问题描述：

在备注中添加换行`<br>`不生效，显示为`<br>`。

**Comment by topcss** [comment]
你直接按回车键就可以换行了，试试看吧。

**Comment by Zhang21** [comment]
@topcss 在md中回车换行后，显示效果了其实并没有空一行。所以才需要`<br>`

**Comment by yangjianan666** [comment]
![default](https://user-images.githubusercontent.com/42053215/49562329-03bcab00-f956-11e8-853f-1c170211342a.png)
如上图所示，我用目前最新版（3.1.0版）编辑备注时，当使用回车进行换行的时候是可以实现“空一行”的，但是无法连续“空两行”。你可以试试呢~

**Comment by yangjianan666** [comment]
> @topcss 在md中回车换行后，显示效果了其实并没有空一行。所以才需要`<br>`

如下图所示，我用目前最新版（3.1.0版）编辑备注时，当使用回车进行换行的时候是可以实现“空一行”的，但是无法连续“空两行”。你可以试试呢~
![image](https://user-images.githubusercontent.com/42053215/49562519-d91f2200-f956-11e8-9041-d449c2c7fb2a.png)
