### ISSUE TITLE
图片不能放大

### ISSUE THREAD

**Issue by shuzeyuxuan** [NaoTu/DesktopNaotu#23]
1. 无法添加本地图片
2.百度脑图线上可以放大图片，但是不论是从百度脑图下载下来的包含图片的文件，还是直接在本地添加的在线图片，都不能查看大图

**Comment by shuzeyuxuan** [comment]
了解

**Comment by topcss** [comment]
版本 v1.0.2 已经提供了图片双击放大的功能，现在可以下载使用了。

**Comment by shuzeyuxuan** [comment]
刚下载试用了一下，可以放大图片了，辛苦了
