### ISSUE TITLE
DesktopNaotu-Windows 版本部分快捷键不能使用

### ISSUE THREAD

**Issue by ZhangSanMo** [NaoTu/DesktopNaotu#33]
DesktopNaotu-Windows 版本部分快捷键不能使用，DesktopNaotu-win32-x64版本正常使用。
具体快捷键比如ALT+UP调整顺序

**Comment by topcss** [comment]
DesktopNaotu-Windows 这个版本目前不算特别稳定，您反馈的这个问题我们正在处理。建议您先用稳定版：
DesktopNaotu-win32-ia32.zip
DesktopNaotu-win32-x64.zip
这个两个都可以用的。
