### ISSUE TITLE
可以自由新建中心主题

### ISSUE THREAD

**Issue by azhon** [NaoTu/DesktopNaotu#37]
可以自由新建中心主题
连接线可以自由添加且连接的的点可以在主题上移动

**Comment by topcss** [comment]
连线是提最多需求的功能，这个功能涉及到和百度脑图从底层分出版本。

这个功能看似简单，却需要花时间研究底层的代码，时间精力成本太高，受益太低。

我只能告诉你，暂时还做不出来，不然也不至于拖这么久才回你。+﹏+

**Comment by azhon** [comment]
😀
