### ISSUE TITLE
BUG：带“#”文件夹路径下启动程序为空白

### ISSUE THREAD

**Issue by czzonet** [NaoTu/DesktopNaotu#38]
# 运行问题

## 环境

win10 64位

## 问题程序版本

win32位和64位

## 描述

- 程序放在带#号目录下打开空白
- 其他目录下启动正常

## 图示

![snipaste_2018-11-09_15-53-31](https://user-images.githubusercontent.com/16220009/48250152-4911b980-e438-11e8-9ef4-1ff3aef133c1.png)

**Comment by topcss** [comment]
很好，会在新版修复这个问题。

**Comment by topcss** [comment]
您好，我这边测试通过了，请下载新版试试看。

如果问题已经解决，请关闭它。

**Comment by czzonet** [comment]
Thank you for a quick response @topcss ! Great work! <3
