### ISSUE TITLE
mac版本建议增加关闭的快捷键

### ISSUE THREAD

**Issue by RogenSH** [NaoTu/DesktopNaotu#43]
如题。

目前退出是没有快捷键的，建议增加。

延伸出来，目前我所使用的v2.0.2018.369版本中，暂时不支持同时打开多个页面，建议支持打开多个页面，然后增加关闭当前页面的选项（以及快捷键

辛苦项目组的大大们~

**Comment by topcss** [comment]
新版 3.1.0 已经加入了开多个窗口的功能，关闭快捷键我们会认真考虑的。

目前发布的顺序是先 windows 和 linux 平台， mac os 会在稍候跟进发布。

**Comment by topcss** [comment]
新版已经加了这个功能，试试看吧。
