### ISSUE TITLE
桌面版脑图 v3.2.0-Beta在windows10家庭版x64上不能正常运行

### ISSUE THREAD

**Issue by StoneAir** [NaoTu/DesktopNaotu#50]
桌面版脑图 v3.2.0-Beta在windows10家庭版x64上不能正常运行，点击后直接成为一个后台进程，在前台桌面什么都不显示。

**Comment by lemonwong** [comment]
win10 x64也这样  教育版

**Comment by topcss** [comment]
撤销了 x64 位的 windows 版本，你们可以先用其他 32位 或者之前的版本。我们解决了会尽快上传 64 位的。

**Comment by topcss** [comment]
已经解决了。你们重新下载一下新版，打开之前需要把用户目录下的这个文件夹删除一下。

C:\Users\用户名\AppData\Roaming\DesktopNaotu
