### ISSUE TITLE
提议: 直接获取剪切板图片

### ISSUE THREAD

**Issue by iostreamrain** [NaoTu/DesktopNaotu#53]
如果能直接粘贴剪切板的图片会大大加快思维导图构建速度, 有些数学公式不能直接输入, 如果能直接粘贴图片会更加方便.

**Comment by topcss** [comment]
可以。这个需求好几个人在提了，我们有时间处理。

**Comment by topcss** [comment]
加了这个功能，你可以在百度云下载新版3.2.2。

**Comment by iostreamrain** [comment]
ありがとう、 超级感谢哈
