### ISSUE TITLE
换行后用4个空格进行排版，内容会被自动划分到子节点

### ISSUE THREAD

**Issue by fastcreate** [NaoTu/DesktopNaotu#58]
您好，由于脑图采用 Tab作为区分父级和子级节点的标记，
所以换行后用4个空格进行排版，内容会被自动划分到子节点，
可否解决下这个问题？又或是能 实现让内容居中显示 就更好了😊

**Comment by fastcreate** [comment]
虽然现在我发现了可以使用 `伪空格` 变通的来解决这个问题，
但还是希望能用空格直接进行排版

**Comment by topcss** [comment]
暂时先用你自己的方法解决吧，改这个比较麻烦，我们会考虑的。

**Comment by mahengrui1** [comment]
> 虽然现在我发现了可以使用 `伪空格符号` 变通的避免情况， 但还是希望能直接进行内容的排版

这就是伪空格符号【ㅤ】（`【`和`】`之间有一个隐藏的符号）
