### ISSUE TITLE
请问能不能考虑增加 Homebrew 安装方式啊？

### ISSUE THREAD

**Issue by suliveevil** [NaoTu/DesktopNaotu#59]
在 macOS 上 brew cask install 安装软件很方便，而且能 brew bundle dump 备份软件列表并通过brew bundle 恢复安装。

```shell
brew cask install XXX
```

**Comment by topcss** [comment]
@ACTom Tom 你熟悉这个吗？你来处理一下？

**Comment by suliveevil** [comment]
主要步骤：

1. fork Homebrew-cask 仓库

2. 终端

  - brew create xxx

  - 测试 audit 和 uninstall

3. PR

**Comment by ACTom** [comment]
好啊，等忙完这段时间我弄下这个

**Comment by leon0707** [comment]
any update?
