### ISSUE TITLE
备注内容为网页链接时，点击后默认在软件内跳转网页，会覆盖掉编辑界面，无法关闭或退回编辑界面。

### ISSUE THREAD

**Issue by fastcreate** [NaoTu/DesktopNaotu#65]
# 备注内容为网页链接时，点击后默认在软件内跳转网页，会覆盖掉编辑界面，无法关闭或退回编辑界面。
## 能否实现软件外部浏览器去跳转网页？或者能在软件内关闭网页或退回编辑界面？

**Comment by jiahe007** [comment]
此问题已经修复完成了,可以下载新版体验了.如果有其他问题,欢迎继续给我们留言哦~(*￣︶￣)
