### ISSUE TITLE
按住Alt进行移动的同时，鼠标选中了一个文本，之后便一直处于移动状态，无法进行编辑操作了

### ISSUE THREAD

**Issue by fastcreate** [NaoTu/DesktopNaotu#66]
### 按住Alt进行移动的同时，鼠标选中了一个文本，之后便一直处于移动状态，无法进行编辑操作了

**Comment by jiahe007** [comment]
能描述的更详细一些吗?

**Comment by jiahe007** [comment]
- 能描述的更详细一些吗?
- 按照这样的格式:
   1. 操作步骤
   2. 截图.gif
- 你说的鼠标选中了一个文本,是选中了窗口内的一个节点还是点了某个文本文档?最好能将复现过程录制成视频.发到咱们的QQ群里,这样更方便查看,也方便开发者进行bug修改.
- QQ群号为: 330722928

**Comment by fastcreate** [comment]
### 回复
提了问题单后就忘记了，刚才加群了，发了录屏，群主说是bug了，在线网页版有同样的问题
谢谢群主提供的解决方案 ：
按住鼠标右键，可以进行拖拽画布，就不会出现该问题

### 建议
快捷键说明中体现一下，相比之下使用Alt+鼠标左键就算没问题了，用起来也比较麻烦
