### ISSUE TITLE
可以别害人了吗？

### ISSUE THREAD

**Issue by yinyunzhao** [NaoTu/DesktopNaotu#67]
写了一下午的脑图，把我之前整理的东西汇总。怕出问题导出所有格式，当时没看km文件。现在图片还在，KM格式的文件是空白，愤怒。真的垃圾。

**Comment by yinyunzhao** [comment]
已经删除软件。简直恶心致死。

**Comment by yangjianan666** [comment]
If you have any question，please say it politely！软件自带『自动保存功能，记录每一步的操作，如果出现文件丢失，完全可以通过github上的指导方法进行找回，你的文件为空白，有可能是你的操作过程有问题导致的。可以试着找一下。』


 
---原始邮件---
发件人: "yinyunzhao"<notifications@github.com>
发送时间: 2019年4月18日(星期四) 上午10:39
收件人: "NaoTu/DesktopNaotu"<DesktopNaotu@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [NaoTu/DesktopNaotu] 可以别害人了吗？ (#67)



已经删除软件。简直恶心致死。

**Comment by topcss** [comment]
**一、情绪部分**

对于您数据丢失，我很抱歉。

我能想象您当时一定很生气和愤怒，觉得自己被伤害了，我数据丢失都是你（开发者）造成的，我再也不想用这个软件了。并且，我说大声的说出来，让更多人知道，不要被它（脑图软件）害了。

我非常理解您的这些感受，并再次对这个软件给您造成的不愉快，说声：对不起。

我知道，`情绪不能被压抑，需要被标明和疏导。`只有被标明之后，正面的情绪会强化，而负面情绪会减弱。

以上这段话，希望能让你感到好受些。如果你感受到不被情绪抓住了，再读下面的内容。; )

**二、问题部分**

github 不是这样用的。在 github 的 isuse  提问题，需要描述清楚问题，操作系统的环境、操作步骤、以及你需要他人怎么帮助你。

这个软件现在至少有几万人在用，遇到各种问题，我们都是通过来沟通解决的。至于`你遇到的情况，可以通过操作日志来恢复数据`。虽然你把软件删除了，数据仍然在你操作系统的用户目录下有备份。

当然，可能你不会再用了，没关系。想告诉你一般成熟的软件，都会有操作日志。而日志可以对内容进行还原。

**三、谈谈我的想法**

这个项目是我用业余时间开发的。昨天11点多还在加班，加班期间还抽空修复了“脑图”的一个问题（bug）。我凭自己的热情来维护这个项目，并真诚的它希望越来越来好，对更多人有用。

这个软件放在网上让大家自愿下载，我尽可能提高它的可用性和好用性。虽然没有任何收入，我仍然坚持在把它做得更好。

今天早上看到你提的isuse。我隔着屏幕都能感受到你的怒气，以及对我的指责。有时候，我们在表达自己的情绪的时候，可以慢一点，这样对自己和别人对是一种保护。

最后希望你有一天改变表达愤怒的方式，用更宽容的心态来对待别人和自己。

**Comment by jiakuan** [comment]
发帖的人，生怕大家不知道他的素质。如此努力的展示。

开源项目作者免费贡献，没有任何报酬。有问题提出来，大家一起沟通改进。这世界没有人有义务免费来伺候这样的傻子。

爱用不用，滚回去多受几年教育再来网上搜索免费软件。不懂得尊重别人的劳动，不懂得沟通，可能属于癌症，受教育可能都没用。人渣！不知道你是怎么养活自己的。

**Comment by liukunc9** [comment]
The ugly always make more troubles

**Comment by 1947324563** [comment]
给作者点赞 3q

**Comment by orchie** [comment]
开源不易 辛苦

**Comment by baltam** [comment]
三连支持！
