### ISSUE TITLE
希望脑图排版更紧凑

### ISSUE THREAD

**Issue by g47603690** [NaoTu/DesktopNaotu#69]
非常喜欢脑图，感谢作者的无私，一直在用脑图，提一点建议，当我的文件非常大之后，电脑屏幕很好，不好浏览，希望增加一个间距选项，让排版更紧凑，这样占用显示屏面积比较小

**Comment by g47603690** [comment]
非常喜欢脑图，感谢作者的无私，一直在用脑图，提一点建议，当我的文件非常大之后，电脑屏幕很小，不好浏览，希望增加一个间距选项，让排版更紧凑，这样占用显示屏面积比较小

**Comment by g47603690** [comment]
看到了，感谢您的回复，请问如何对项目组进行捐赠

**Comment by jiahe007** [comment]
> 看到了，感谢您的回复，请问如何对项目组进行捐赠

- 刚刚和项目组的老大商量了一下，新加了一个捐赠的账户；
- 使用微信捐赠的方式，捐赠金额随用户心意而定；
- 虽然增加了捐赠方法，但是我们的初衷是不变的，无论金额多少，都是一份心意，我们会继续努力将 **`爱脑图（inaotu）`** 做好的；
- 同时也欢迎你继续关注和使用 **`爱脑图`** 来 **`构建自己的新的生活和工作方式`**。

项目捐赠二维码：
![捐赠方式](https://user-images.githubusercontent.com/42053215/56706836-06733d80-6749-11e9-9505-1550b1e0f75e.png)
