### ISSUE TITLE
增加节点全部展开功能

### ISSUE THREAD

**Issue by imaojun** [NaoTu/DesktopNaotu#77]
由于需要到处SVG格式，所以需要将子节点全部展开方便导出。

如果子节点较多，需要每次手动点击展开子节点比较麻烦，而且容易遗漏个别子节点的展开。

希望可以提供一键展开全部节点和一键关闭所有节点的功能。

**Comment by topcss** [comment]
菜单：视图 > 展开

看了下，支持6级节点展开。
