### ISSUE TITLE
文件关联及缩略图

### ISSUE THREAD

**Issue by TheHot** [NaoTu/DesktopNaotu#86]
希望能够增加km文件关联程序功能，虽然自己改注册表可以做到，不过win10还是没有这个km后缀的文件关联设置

**Comment by topcss** [comment]
Win 10 按如下步骤操作：

1. 把下面内容保存文件 linkNaotuApp.bat
2. 把 `D:\DesktopNaotu-win32-ia32\` 改为你电脑的路径
3. 以管理员身份运行

``` CMD
assoc .km=naotuApp
ftype naotuApp=D:\DesktopNaotu-win32-ia32\DesktopNaotu.exe %1
```

**Comment by TheHot** [comment]
感谢！
