### ISSUE TITLE
关于快捷键冲突

### ISSUE THREAD

**Issue by TheHot** [NaoTu/DesktopNaotu#89]
平台：Windows
问题：使用自定义快捷键Ctrl+Shift+D时，会唤起脑图，并且在脑图中打开浏览器的审查元素
建议：希望能屏蔽除了脑图自带的快捷方式之外的组合键

**Comment by topcss** [comment]
这么巧吗，哈哈。你可以暂时先用其他的快捷键组合，有空给你改。

**Comment by TheHot** [comment]
嘿嘿，好嘞，真的挺好用，希望能一直更新下去，支持一波！
