### ISSUE TITLE
Ubuntu系统下如何切换语言为简体中文？V3.2.3

### ISSUE THREAD

**Issue by ictw** [NaoTu/DesktopNaotu#91]
## Ubuntu 18.04系统下如何切换语言为简体中文？版本V3.2.3

**Comment by QPJIANG** [comment]
~/.config/desktopnaotu/naotu.config.json  中配置locale 

或
删除~/.config/desktopnaotu/naotu.config.json ，
export LANG=zh_CN.UTF-8
export LC_ALL=zh_CN.UTF-8
然后再运行
