### ISSUE TITLE
在Ubuntu 18 平台上不能运行 

### ISSUE THREAD

**Issue by WuXu-CN** [NaoTu/DesktopNaotu#99]
下载版本:  DesktopNaotu-linux-x64.zip
运行环境: Ubuntu18

解压后运行 DesktopNaotu

错误提示:
无法显示"DesktopNaotu"
没有安装处理"可执行文件"文件的应用程序

新手 不明白怎么用  谢谢各位大佬

**Comment by WuXu-CN** [comment]
已经解决 为后来看到的同学 参考
原因是未能给DesktopNaotu这个可执行文件添加可执行文件的权限,所以操作系统未能按可执行文件运行
在属性中将允许作为可执行文件勾选 即可运行

**Comment by ProfessorX** [comment]
解决了老哥还不把issue关了。
